 SELECT * FROM emp;
 SELECT ename FROM emp;
 SELECT ename, sal FROM emp;
 SELECT ename, comm FROM emp;
 SELECT empno, deptno FROM emp;
 SELECT ename, hiredate FROM emp;
 SELECT ename, job FROM emp;
 SELECT ename, job, sal FROM emp;
 SELECT dname FROM dept;
 SELECT dname, loc FROM dept;
 SELECT ename, sal * 12 AS annual_salary FROM emp;
 SELECT ename, job, sal * 6 AS half_term_salary FROM emp;
 SELECT emp.*, sal * 12 + 2000 AS annual_salary_with_bonus FROM emp;
 SELECT ename, sal, sal * 1.10 AS salary_after_hike FROM emp;
 SELECT ename, sal * 0.75 AS salary_after_deduction FROM emp;
 SELECT ename, sal + 50 AS salary_after_hike FROM emp;
 SELECT ename, (sal * 12) * 0.90 AS annual_salary_after_deduction FROM emp;
 SELECT ename, sal + ifnull(comm, 0) AS total_salary FROM emp;
 SELECT emp.*, sal * 12 AS annual_salary FROM emp;
 SELECT ename, job, sal - 100 AS salary_after_penalty FROM emp;