SELECT UPPER(ST_NAME) FROM STUDENT;

SELECT LOWER(ST_NAME) FROM STUDENT;

SELECT ST_NAME, LENGTH(ST_NAME) FROM STUDENT;

SELECT REVERSE(ST_NAME) FROM STUDENT;

SELECT ST_NAME || ' lives in ' || ST_CITY FROM STUDENT;

SELECT REPLACE(ST_EMAIL, 'gmail', 'outlook') FROM STUDENT;

SELECT SUBSTR(ST_NAME, 1, 3) FROM STUDENT;

SELECT ST_NAME, INSTR(UPPER(ST_NAME), 'A') FROM STUDENT;

SELECT LPAD(ST_NAME, 10, '*') FROM STUDENT;

SELECT RPAD(ST_NAME, 12, '#') FROM STUDENT;

SELECT SUBSTR(ST_NAME, 1, 2) FROM STUDENT;

SELECT SUBSTR(ST_NAME, -2) FROM STUDENT;

SELECT ASCII(SUBSTR(ST_NAME, 1, 1)) FROM STUDENT;

SELECT ST_MARKS, MOD(ST_MARKS, 10) FROM STUDENT;

SELECT ROUND(ST_MARKS, -1) FROM STUDENT;

SELECT ST_MARKS - (ST_MARKS % 10) FROM STUDENT;

SELECT SQRT(ST_MARKS) FROM STUDENT;

SELECT ABS(ST_MARKS) FROM STUDENT;

SELECT ST_NAME, ADMISSION_DT FROM STUDENT;

SELECT ST_NAME,
       TIMESTAMPDIFF(YEAR, ADMISSION_DT, CURDATE())
FROM STUDENT;


SELECT ST_NAME,
       DATE_ADD(ADMISSION_DT, INTERVAL 6 MONTH)
FROM STUDENT;


SELECT ST_NAME,
       DATE_FORMAT(ADMISSION_DT, '%d-%m-%Y')
FROM STUDENT;


SELECT ST_NAME,
       DAYNAME(ADMISSION_DT)
FROM STUDENT;


SELECT ST_NAME,
       CASE
           WHEN ST_MARKS >= 75 THEN 'Pass'
           ELSE 'Fail'
       END
FROM STUDENT;

SELECT IFNULL(ST_EMAIL, 'Not Provided') FROM STUDENT;


SELECT
    CASE
        WHEN ST_CITY = 'Delhi' THEN NULL
        ELSE ST_CITY
    END
FROM STUDENT;

SELECT COALESCE(ST_EMAIL, 'Not Provided') FROM STUDENT;

